r"""Fill the department's Project Proposal template with this project's content.

The department supplies the layout as a .docx (paper/Proposal_template.docx), so the
proposal is produced by *editing that file* rather than by re-creating the layout in
LaTeX: every paragraph here is cloned from a paragraph the template already contains,
which is the only way to guarantee the fonts, sizes, list numbering and indents are
byte-for-byte what the department asked for.

The voice throughout is a proposal -- what the system *will* do and how it *will* be
built -- not a report of finished work.

By default the template's own measurements are left exactly as issued, even where
they print outside the margins the section declares (the department's reference
paragraphs carry ind right="-630", and both tables carry tblInd="-318"). Pass
--fit-margins to pull those back inside the 1 in margins instead.

    python src/build_proposal.py                # docx + pdf, template exactly as issued
    python src/build_proposal.py --fit-margins  # ... but nothing outside the margins
    python src/build_proposal.py --skip-pdf

Writes output/paper/Project_Proposal.docx and .pdf.
"""
from __future__ import annotations

import argparse
import copy
import re
import shutil
import struct
import subprocess
import sys
import zipfile
from pathlib import Path

from lxml import etree

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "paper" / "Proposal_template.docx"
FIG = ROOT / "output" / "figures" / "architecture.png"
OUTDIR = ROOT / "output" / "paper"
SOFFICE = Path(r"E:\tools\libreoffice\program\soffice.com")

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
NS = {"w": W[1:-1]}
XML = "{http://www.w3.org/XML/1998/namespace}"

PH = "[TO BE FILLED]"

# Page is US Letter with 1 in margins -> a 6.5 in text column.
TEXT_W_EMU = int(6.5 * 914400)


# --------------------------------------------------------------------------- content

TITLE = ("Watermark-Guided Tamper Localization and Recovery: A Key-Seeded "
         "Self-Embedding Fragile Watermarking Scheme with Joint Localization "
         "and Restoration Assessment")

ABSTRACT = (
    "Digital images are relied upon as records, yet the formats they are stored in "
    "protect nothing about their content. Passive forensic detectors can indicate "
    "that a region was altered but cannot restore what was destroyed, and their "
    "learned instances need annotated corpora and accelerator hardware. This project "
    "will develop the active alternative: a deterministic, training-free "
    "self-embedding fragile watermarking system. The image will be partitioned into "
    "8×8 blocks, and the two least-significant bit-planes of each block will "
    "carry a 32-bit keyed authentication tag computed over that block's six "
    "most-significant bit-planes, together with a 96-bit compressed recovery "
    "descriptor of a spatially distant partner block chosen by a key-seeded "
    "permutation. Verification will recompute each tag to localize tampering at block "
    "granularity, rebuild flagged blocks from surviving partners, and mark the "
    "remainder explicitly unrecoverable rather than fabricating content. The system "
    "will be evaluated across four tamper classes and three tamper ratios, reporting "
    "imperceptibility, localization and recovery together."
)

KEYWORDS = ("Fragile watermarking; self-embedding; tamper localization; image "
            "authentication; content recovery; block mapping; keyed hashing; "
            "digital image forensics.")

PROBLEM = [
    "Given a digital image stored in a lossless container and a secret key held by "
    "the authenticating party, the system to be built must embed authentication and "
    "recovery information into the image itself, so that at any later point three "
    "questions can be answered from the received image alone.",

    "**First**, was the image modified, and if so, exactly where? The modified region "
    "must be localized to the block grid without reference to the original image and "
    "without any external database or side-channel, because in the applications that "
    "motivate this work the original is precisely what is unavailable.",

    "**Second**, what was there before? The original content of the modified region "
    "must be approximately restored from information that survived elsewhere inside "
    "the same image, not generated by inference. A reconstruction that is merely "
    "plausible has no evidentiary value.",

    "**Third**, what cannot be restored? Any region whose backup was itself destroyed "
    "must be reported as unrecoverable rather than filled in, so that the output "
    "never presents invented content as recovered content.",

    "The embedding must be perceptually transparent, the verification decision must "
    "be deterministic and independently recomputable by any third party holding the "
    "key, and the whole pipeline must run on a commodity CPU with no trained "
    "parameters and no accelerator.",
]

ARCH_INTRO = (
    "The system will be built as four decoupled stages. Stage 1 embeds at or near "
    "acquisition; Stage 2 is the tampering the harness will simulate; Stage 3 "
    "verifies and localizes at any later point; Stage 4 recovers. Only the received "
    "image, the key and the image identifier will be required at verification time "
    "\u2014 no original and no reference database. The block diagram below shows the "
    "data flow to be implemented."
)

ARCH_AFTER = [
    "**Stage 1 \u2014 Embedding.** The image will be split into 8\u00d78 blocks. For "
    "every block the six most-significant bit-planes will be projected out (the MSB "
    "view, a & 0xFC) and a 96-bit recovery descriptor computed from it. A key-seeded "
    "permutation will assign each block a distant partner, and each block will be "
    "written with 128 bits into its two least-significant bit-planes: its partner's "
    "96-bit descriptor plus a 32-bit truncated keyed HMAC-SHA256 tag binding the "
    "block index, the image identifier, the MSB view and the descriptor being "
    "carried. Because the tag is computed over the MSB view only, and only LSBs are "
    "written, embedding cannot invalidate what it has just signed \u2014 so a single "
    "pass will suffice, with no iteration to a fixed point.",

    "**Stage 3 \u2014 Verification and localization.** Verification will re-derive "
    "the same subkeys from the key, read the stored payload out of the two LSB "
    "planes, recompute each block's tag from the block's current MSB view, and "
    "compare. Any mismatch flags that block. The flagged set will be refined by a "
    "neighbourhood rule and expanded to a pixel mask. Every decision will be recorded "
    "in a per-block audit record so a third party holding the key can repeat it.",

    "**Stage 4 \u2014 Recovery.** The flagged set will be partitioned into blocks "
    "whose partner survived and blocks whose partner did not. The first group will be "
    "rebuilt from the descriptor the surviving partner carries; the second will be "
    "marked unrecoverable and left visibly flagged. The recoverability rate "
    "\u03c1 = 1 \u2212 |U|/|T| will be reported alongside every recovery figure, so "
    "that reconstruction quality is never quoted without its coverage.",
]

MODULES = [
    "**Payload foundation** \u2014 key derivation with domain-separated subkeys, bit "
    "budget, block geometry, MSB projection, keyed tag computation, descriptor "
    "encoding and decoding, and LSB packing. Every other module will import it, so "
    "the constants exist in exactly one place.",
    "**Block mapper** \u2014 builds the key-seeded single-cycle permutation, enforces "
    "the minimum spatial separation between a block and its partner, and self-checks "
    "bijectivity, absence of fixed points and the separation bound before returning.",
    "**Embedder** \u2014 Stage 1. Computes descriptors, permutes them, computes the "
    "binding tags and writes both into the two LSB planes, asserting that the six MSB "
    "planes are untouched.",
    "**Detector and localizer** \u2014 Stage 3. Extracts the stored payload, "
    "recomputes tags, produces the block-level tamper mask, applies neighbourhood "
    "refinement and expands to a pixel mask.",
    "**Recovery engine** \u2014 Stage 4. Splits the flagged set into recoverable and "
    "unrecoverable, rebuilds the former from partner descriptors, marks the latter, "
    "and reports \u03c1.",
    "**Tamper harness** \u2014 generates the four tamper classes with exact "
    "ground-truth masks and the achieved tamper ratio, so that scoring never depends "
    "on the detector under test.",
    "**Metrics and evaluation** \u2014 PSNR, SSIM, confusion counts, localization "
    "scores, in-region recovery metrics, and the CSV result grid.",
    "**Automated gate** \u2014 validates the result grid against expected bands and "
    "refuses to emit any table or figure if a check fails, so no number can reach the "
    "report without passing it.",
    "**Applications** \u2014 a local web application and a demonstration interface "
    "built over the same pipeline, with no duplicated numerics.",
]

LIT = [
    "**Passive forensics and learned detectors.** Passive methods analyse the "
    "received image alone. Zhou et al. [13] use a two-stream RGB and noise-residual "
    "architecture for splice localization, and ManTra-Net [14] uses self-supervised "
    "anomaly features to localize forgeries without training on the specific "
    "manipulation. **Pros:** they need no cooperation at capture time and work on "
    "arbitrary images. **Cons:** they require annotated corpora and accelerator "
    "hardware, their output is a per-pixel confidence rather than an auditable "
    "decision, and they cannot restore destroyed content.",

    "**Active watermarking.** Active schemes insert authentication information before "
    "distribution, so verification becomes a decision about self-consistency. Robust "
    "watermarks [2] survive processing and serve copyright; fragile watermarks [5], "
    "[6] break under any change and serve authentication; semi-fragile schemes [4] "
    "sit between. Holliman and Memon [3] showed that block-independent schemes admit "
    "counterfeiting by block transplantation, and Fridrich [7] showed that "
    "localization granularity trades against security \u2014 both results directly "
    "constrain the design proposed here, and are the reason the tag will bind the "
    "block index and image identifier as well as the content.",

    "**Self-embedding and content recovery.** Fridrich and Goljan [1] introduced "
    "hiding a compressed version of each region elsewhere in the same image; Lin et "
    "al. [8] added a hierarchical structure. **Pros:** the backup travels with the "
    "image and needs no database. **Cons:** the backup occupies payload capacity and "
    "can itself be destroyed.",

    "**The tamper coincidence problem.** If a block and its backup fall inside the "
    "same tampered region, both are lost. AuSR3 [16] addresses this with a block "
    "mapping that guarantees a minimum spatial distance between a block and its "
    "partner. This project adopts that idea and credits it; it is not claimed as a "
    "contribution.",

    "**Reference sharing and fountain-coded allocation.** Zhang et al. [9] and Korus "
    "and Dziech [10] allocate reference bits across many blocks rather than one-to-"
    "one, so recovery degrades gracefully at high tamper ratios. This is stronger "
    "than one-to-one mapping under dispersed attack and is the identified upgrade "
    "path for this work, stated here rather than concealed.",

    "**Learned proactive watermarking.** EditGuard [17] embeds a learned watermark "
    "that both localizes and recovers. **Pros:** strong reported accuracy. **Cons:** "
    "training data, GPU inference and a model artefact to version and defend. No "
    "accuracy claim will be made against it; the distinction pursued here is "
    "determinism and auditability, not accuracy.",
]

MARKET = [
    "Deployed products fall into four groups, none of which offers localization and "
    "recovery together from inside the image itself.",

    "**Provenance metadata (C2PA Content Credentials).** A cryptographically signed "
    "manifest recording an asset's origin and edit history. **Pros:** an open standard "
    "with camera and editing-software backing. **Cons:** the manifest lives beside the "
    "pixels, so re-encoding, a screenshot or a metadata strip removes it entirely, "
    "and it can never restore content \u2014 it attests to history rather than "
    "protecting it.",

    "**Controlled-capture services (Truepic and similar).** Authenticate images at "
    "the moment of capture through a proprietary pipeline. **Pros:** strong provenance "
    "where deployed. **Cons:** require the vendor's software and infrastructure, and do "
    "not recover destroyed content.",

    "**Forensic analysis tools (Amped Authenticate, FotoForensics-style services).** "
    "Apply passive heuristics \u2014 error-level analysis, noise and CFA "
    "inconsistency, metadata review \u2014 with no prior cooperation. **Pros:** work on "
    "arbitrary images. **Cons:** results need expert interpretation, carry no ground "
    "truth, and offer no restoration.",

    "**Whole-file digital signatures (as standardized for DICOM).** **Pros:** "
    "mathematically decisive and already deployed in hospital systems. **Cons:** detect "
    "only that a file changed \u2014 they neither localize the change to a region nor "
    "recover it.",

    "**Research gap.** The gap in the market mirrors the gap in the literature: "
    "existing products either attest to provenance externally or analyse pixels after "
    "the fact, and none embeds recoverable content inside the image so that a damaged "
    "region can be restored from what survived. The gap this project will address is "
    "stated narrowly and deliberately. It is not the distant-mapping idea, which is "
    "credited to AuSR3 [16], and it is not superiority over learned proactive "
    "watermarking [17]. It is threefold: a construction in which every positive "
    "detection reduces to one recomputed keyed hash comparison that a third party can "
    "repeat bit for bit; an explicit keyed construction with each field binding "
    "stated and analysed, including what each binding defeats; and joint evaluation, "
    "in which imperceptibility, localization and recovery are reported together with "
    "the unrecoverable fraction disclosed rather than excluded.",
]

OBJECTIVES = [
    "To design a per-block payload that fits entirely within two least-significant "
    "bit-planes, so that the embedding distortion is analytically bounded before a "
    "single image is processed, and to achieve mean imperceptibility of at least "
    "40 dB PSNR over a standard corpus.",
    "To construct a key-seeded block mapping that is provably bijective, free of "
    "fixed points and short cycles, and that enforces a minimum spatial separation "
    "between a block and its recovery partner, so that a localized attack cannot "
    "destroy both.",
    "To localize region-level tampering at block granularity with block-level recall "
    "of 1.0 across four distinct tamper classes and three tamper ratios.",
    "To produce zero false positives on unmodified watermarked images, verified over "
    "a null condition of more than one million independent block verifications.",
    "To reconstruct flagged regions from partner-held descriptors, report an explicit "
    "recoverability rate, and mark unrecoverable regions rather than fabricating "
    "content for them.",
    "To deliver a reproducible evaluation grid and working software, gated by "
    "automated checks that must pass before any result is reported.",
]

SCOPE = [
    "**In scope.** Still images, greyscale and three-channel colour, at 8 bits per "
    "channel, stored in lossless containers (PNG, BMP, TIFF). Block sizes 8 and 4, so "
    "that the resolution against payload trade-off can be measured rather than "
    "asserted. Two recovery descriptor designs to be evaluated against each other. "
    "Four tamper classes \u2014 copy-paste splicing, object removal by inpainting, "
    "crop-and-refill, and random block corruption \u2014 at three tamper ratios. A "
    "fixed 32-image evaluation corpus, every file pinned by SHA-256 so the corpus "
    "reproduces byte for byte. A local web application and a demonstration interface "
    "over the same pipeline.",

    "**Out of scope.** Video and audio. Robustness to lossy re-encoding, resizing, "
    "rotation or filtering \u2014 the scheme is fully fragile by design, and any "
    "change to the pixels is intended to break it. Adversaries in possession of the "
    "secret key, against whom no active scheme can defend. Real-time embedding inside "
    "camera firmware, which is an engineering integration rather than a research "
    "question. Comparison against learned detectors on their own accuracy terms.",
]

REQUIREMENTS = [
    "**Language.** Python 3.10 or newer. Cryptographic primitives will be taken from "
    "the standard library (hashlib, hmac, struct); no third-party cryptography will "
    "be introduced.",
    "**Core libraries.** NumPy, OpenCV (headless), scikit-image and Pillow, each "
    "pinned to an exact version so that a result can be reproduced later.",
    "**Interface libraries.** Flask for the local web application, Streamlit for the "
    "demonstration interface, Matplotlib for figures.",
    "**Storage.** SQLite for the local library of protected images.",
    "**Machine learning.** None. No framework, no trained parameters, and no model "
    "artefact to version \u2014 this is a design decision, not a limitation.",
    "**Processor.** Any commodity x86-64 or ARM CPU; execution is single-threaded.",
    "**Accelerator.** No GPU at any stage \u2014 embedding, verification or recovery.",
    "**Memory and storage.** 8 GB RAM and about 2 GB of disk for the corpus, the "
    "result grid and the generated figures.",
    "**Operating system.** Platform independent; development and testing will be on "
    "Windows, with no OS-specific dependency.",
    "**Document build (optional).** tectonic and pandoc, required only to rebuild the "
    "paper and this proposal.",
]

OUTCOMES = [
    "The deliverable will be a working, reproducible pipeline together with the "
    "evidence needed to defend it. The targets below are the criteria against which "
    "the project will judge itself.",

    "**Imperceptibility.** Mean PSNR of at least 40 dB with SSIM above 0.98 over the "
    "32-image corpus, for every descriptor variant.",

    "**Localization.** Block-level recall of 1.0 across all tamper classes and "
    "ratios, with pixel-level precision reported as the informative figure. Block-"
    "level precision will deliberately not be headlined: under the ground-truth rule "
    "used here a block-level false positive is structurally impossible, so that "
    "metric would read 1.000 regardless of detector quality.",

    "**False positives.** Zero false-positive blocks over a null condition of more "
    "than one million independent verifications on unmodified watermarked images, "
    "reported as a determinism and implementation-consistency check \u2014 not as a "
    "statistical bound on the cryptographic false-accept probability, which that "
    "experiment does not measure.",

    "**Recovery.** An explicit recoverability rate \u03c1 reported at every tamper "
    "ratio, in-region recovery quality reported separately from whole-image quality, "
    "and every unrecoverable region marked rather than filled. We expect in-region "
    "quality to stay roughly flat as the tamper ratio grows while whole-image quality "
    "falls, which would identify mapping coverage rather than descriptor fidelity as "
    "the dominant constraint \u2014 and would point directly at reference sharing as "
    "the highest-value extension.",

    "**Reproducibility.** A complete result grid in CSV, generated tables and figures, "
    "an automated gate that must pass before any number is quoted, and an end-to-end "
    "test that a third party can run from a clean clone.",

    "**Dissemination.** An IEEE-format manuscript prepared for submission to a "
    "peer-reviewed venue in image forensics or multimedia security \u2014 the IEEE "
    "International Workshop on Information Forensics and Security (WIFS) and the IEEE "
    "International Conference on Image Processing (ICIP) are the two candidate venues "
    "identified, both appropriate in scope.",
]

PLAN = [
    ("1", "Literature survey and problem formulation", "Survey and gap statement"),
    ("2", "Scheme design: bit budget, tag construction, block mapping",
     "Design specification"),
    ("3", "Implementation of the core pipeline", "Embed, detect and recover modules"),
    ("4", "Tamper harness and metrics", "Four tamper classes with exact masks"),
    ("5", "Full experimental grid and validation", "Result grid and automated gate"),
    ("6", "Applications and adversarial testing", "Web application and demo interface"),
    ("7", "Paper preparation and internal review", "IEEE-format manuscript"),
    ("8", "Reference-sharing extension", "Prototype and comparison"),
    ("9", "Final report, demonstration and viva", "Report, presentation, submission"),
]

REFERENCES = [
    "[1] J. Fridrich and M. Goljan, \u201cProtection of digital images using "
    "self-embedding,\u201d in Proc. Symp. Content Security and Data Hiding in Digital "
    "Media, Newark, NJ, USA, May 1999.",
    "[2] I. J. Cox, J. Kilian, F. T. Leighton, and T. Shamoon, \u201cSecure spread "
    "spectrum watermarking for multimedia,\u201d IEEE Trans. Image Process., vol. 6, "
    "no. 12, pp. 1673\u20131687, Dec. 1997.",
    "[3] M. Holliman and N. Memon, \u201cCounterfeiting attacks on oblivious "
    "block-wise independent invisible watermarking schemes,\u201d IEEE Trans. Image "
    "Process., vol. 9, no. 3, pp. 432\u2013441, Mar. 2000.",
    "[4] C.-Y. Lin and S.-F. Chang, \u201cSemi-fragile watermarking for "
    "authenticating JPEG visual content,\u201d in Proc. SPIE 3971, Security and "
    "Watermarking of Multimedia Contents II, 2000, pp. 140\u2013151.",
    "[5] P. W. Wong and N. Memon, \u201cSecret and public key image watermarking "
    "schemes for image authentication and ownership verification,\u201d IEEE Trans. "
    "Image Process., vol. 10, no. 10, pp. 1593\u20131601, Oct. 2001.",
    "[6] C. Rey and J.-L. Dugelay, \u201cA survey of watermarking algorithms for "
    "image authentication,\u201d EURASIP J. Appl. Signal Process., vol. 2002, no. 6, "
    "pp. 613\u2013621, 2002.",
    "[7] J. Fridrich, \u201cSecurity of fragile authentication watermarks with "
    "localization,\u201d in Proc. SPIE 4675, Security and Watermarking of Multimedia "
    "Contents IV, San Jose, CA, USA, Jan. 2002, pp. 691\u2013700.",
    "[8] P.-L. Lin, C.-K. Hsieh, and P.-W. Huang, \u201cA hierarchical digital "
    "watermarking method for image tamper detection and recovery,\u201d Pattern "
    "Recognit., vol. 38, no. 12, pp. 2519\u20132529, Dec. 2005.",
    "[9] X. Zhang, S. Wang, Z. Qian, and G. Feng, \u201cReference sharing mechanism "
    "for watermark self-embedding,\u201d IEEE Trans. Image Process., vol. 20, no. 2, "
    "pp. 485\u2013495, Feb. 2011.",
    "[10] P. Korus and A. Dziech, \u201cEfficient method for content reconstruction "
    "with self-embedding,\u201d IEEE Trans. Image Process., vol. 22, no. 3, "
    "pp. 1134\u20131147, Mar. 2013.",
    "[11] Z. Wang, A. C. Bovik, H. R. Sheikh, and E. P. Simoncelli, \u201cImage "
    "quality assessment: From error visibility to structural similarity,\u201d IEEE "
    "Trans. Image Process., vol. 13, no. 4, pp. 600\u2013612, Apr. 2004.",
    "[12] National Institute of Standards and Technology, \u201cSecure Hash Standard "
    "(SHS),\u201d FIPS Publication 180-4, Aug. 2015.",
    "[13] P. Zhou, X. Han, V. I. Morariu, and L. S. Davis, \u201cLearning rich "
    "features for image manipulation detection,\u201d in Proc. IEEE/CVF Conf. Computer "
    "Vision and Pattern Recognition (CVPR), Salt Lake City, UT, USA, Jun. 2018.",
    "[14] Y. Wu, W. AbdAlmageed, and P. Natarajan, \u201cManTra-Net: Manipulation "
    "tracing network for detection and localization of image forgeries with anomalous "
    "features,\u201d in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition "
    "(CVPR), Long Beach, CA, USA, Jun. 2019.",
    "[15] A. Aminuddin and F. Ernawan, \u201cAuSR1: Authentication and self-recovery "
    "using a new image inpainting technique with LSB shifting in fragile image "
    "watermarking,\u201d J. King Saud Univ. \u2013 Comput. Inf. Sci., 2022.",
    "[16] A. Aminuddin and F. Ernawan, \u201cAuSR3: A new block mapping technique for "
    "image authentication and self-recovery to avoid the tamper coincidence "
    "problem,\u201d J. King Saud Univ. \u2013 Comput. Inf. Sci., vol. 35, no. 9, "
    "art. 101755, 2023.",
    "[17] X. Zhang, R. Li, J. Yu, Y. Xu, W. Li, and J. Zhang, \u201cEditGuard: "
    "Versatile image watermarking for tamper localization and copyright "
    "protection,\u201d in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition "
    "(CVPR), 2024.",
    "[18] University of Southern California, Signal and Image Processing Institute, "
    "\u201cThe USC-SIPI Image Database.\u201d [Online]. Available: "
    "https://sipi.usc.edu/database/",
]


# ------------------------------------------------------------------------- xml tools

def text_of(p) -> str:
    return "".join(t.text or "" for t in p.iter(W + "t"))


def set_text(p, s: str):
    """Replace a cloned paragraph's runs with `s`, honouring **bold** segments.

    The run properties are taken from the paragraph's own first run, so the clone
    keeps the template's font and size instead of inheriting whatever Word decides.
    """
    runs = p.findall(W + "r")
    proto = copy.deepcopy(runs[0]) if runs else etree.SubElement(p, W + "r")
    for r in runs:
        p.remove(r)
    marked = "**" in s
    for i, seg in enumerate(s.split("**")):
        if not seg:
            continue
        r = copy.deepcopy(proto)
        for t in r.findall(W + "t"):
            r.remove(t)
        rPr = r.find(W + "rPr")
        if rPr is None:
            rPr = etree.Element(W + "rPr")
            r.insert(0, rPr)
        if marked:                      # odd segments were between ** markers
            b = rPr.find(W + "b")
            if i % 2:
                if b is None:
                    rPr.insert(0, etree.Element(W + "b"))
            elif b is not None:
                rPr.remove(b)
        t = etree.SubElement(r, W + "t")
        t.set(XML + "space", "preserve")
        t.text = seg.replace("'", "’")
        p.append(r)
    return p


def clone(proto, s: str = ""):
    return set_text(copy.deepcopy(proto), s)


def png_size(path: Path):
    """Width and height in pixels, straight out of the IHDR chunk."""
    head = path.read_bytes()[:24]
    assert head[:8] == b"\x89PNG\r\n\x1a\n", f"{path} is not a PNG"
    return struct.unpack(">II", head[16:24])


def drawing_paragraph(proto, rel_id: str, cx: int, cy: int):
    """A centred paragraph holding one inline image."""
    p = clone(proto, "")
    for r in p.findall(W + "r"):
        p.remove(r)
    pPr = p.find(W + "pPr")
    if pPr is not None:
        for tag in ("jc", "ind"):
            for el in pPr.findall(W + tag):
                pPr.remove(el)
        put(pPr, "jc", PPR_ORDER, val="center")
    xml = f"""<w:r xmlns:w="{NS['w']}"
        xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
        xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
        xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"
        xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
      <w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0">
        <wp:extent cx="{cx}" cy="{cy}"/>
        <wp:docPr id="101" name="Architecture" descr="System architecture"/>
        <a:graphic><a:graphicData
            uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
          <pic:pic>
            <pic:nvPicPr>
              <pic:cNvPr id="0" name="architecture.png"/><pic:cNvPicPr/>
            </pic:nvPicPr>
            <pic:blipFill><a:blip r:embed="{rel_id}"/>
              <a:stretch><a:fillRect/></a:stretch></pic:blipFill>
            <pic:spPr><a:xfrm><a:off x="0" y="0"/>
              <a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
              <a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr>
          </pic:pic>
        </a:graphicData></a:graphic>
      </wp:inline></w:drawing></w:r>"""
    p.append(etree.fromstring(xml))
    return p


# CT_PPr and CT_TblPrBase are sequences, not bags: Word (and the OOXML schema)
# reject a pPr whose ind lands after rPr, or a tblPr whose tblLayout lands after
# tblLook, even though both render fine in LibreOffice.
PPR_ORDER = ["pStyle", "keepNext", "keepLines", "pageBreakBefore", "framePr",
             "widowControl", "numPr", "suppressLineNumbers", "pBdr", "shd", "tabs",
             "suppressAutoHyphens", "kinsoku", "wordWrap", "overflowPunct",
             "topLinePunct", "autoSpaceDE", "autoSpaceDN", "bidi", "adjustRightInd",
             "snapToGrid", "spacing", "ind", "contextualSpacing", "mirrorIndents",
             "suppressOverlap", "jc", "textDirection", "textAlignment",
             "textboxTightWrap", "outlineLvl", "divId", "cnfStyle", "rPr", "sectPr",
             "pPrChange"]
TBLPR_ORDER = ["tblStyle", "tblpPr", "tblOverlap", "bidiVisual", "tblStyleRowBandSize",
               "tblStyleColBandSize", "tblW", "jc", "tblCellSpacing", "tblInd",
               "tblBorders", "shd", "tblLayout", "tblCellMar", "tblLook", "tblCaption",
               "tblDescription", "tblPrChange"]


def put(parent, name, order, **attrs):
    """Insert (or update) a child at its schema-mandated position."""
    el = parent.find(W + name)
    if el is None:
        el = etree.Element(W + name)
        rank = order.index(name)
        after = [c for c in parent
                 if etree.QName(c).localname in order
                 and order.index(etree.QName(c).localname) > rank]
        if after:
            after[0].addprevious(el)
        else:
            parent.append(el)
    for k, v in attrs.items():
        el.set(W + k, v)
    return el


TEXT_W = 9360   # twips: US Letter less two 1 in margins


def fit_table(tbl):
    """Scale a table to the text block and pin the layout.

    Without a fixed layout LibreOffice re-autofits from the cell contents and the
    template's team table -- which is wider than the text block -- prints its last
    column past the right margin.
    """
    grid = tbl.find(W + "tblGrid")
    cols = grid.findall(W + "gridCol") if grid is not None else []
    if not cols:
        return
    want = [int(c.get(W + "w")) for c in cols]
    total = sum(want)
    scaled = [wd * TEXT_W // total for wd in want]
    scaled[-1] += TEXT_W - sum(scaled)
    for c, wd in zip(cols, scaled):
        c.set(W + "w", str(wd))
    tblPr = tbl.find(W + "tblPr")
    put(tblPr, "tblW", TBLPR_ORDER, w=str(TEXT_W), type="dxa")
    put(tblPr, "tblLayout", TBLPR_ORDER, type="fixed")
    for tr in tbl.findall(W + "tr"):
        for tc, wd in zip(tr.findall(W + "tc"), scaled):
            tcW = tc.find(W + "tcPr/" + W + "tcW")
            if tcW is not None:
                tcW.set(W + "w", str(wd))
                tcW.set(W + "type", "dxa")


def zero_indent(p):
    """Table cells must not inherit the body's first-line indent, or the first
    line of every cell starts short and the cell wraps a word early."""
    pPr = p.find(W + "pPr")
    if pPr is None:
        pPr = etree.Element(W + "pPr")
        p.insert(0, pPr)
    put(pPr, "ind", PPR_ORDER,
        **{k: "0" for k in ("firstLine", "left", "right", "start", "end")})
    return p


def plan_table(proto_tbl, proto_p):
    """Clone the template's team table and rebuild it as the schedule."""
    tbl = copy.deepcopy(proto_tbl)
    rows = tbl.findall(W + "tr")
    header, blank = rows[0], rows[1]
    for r in rows:
        tbl.remove(r)

    widths = [720, 4680, 3960]           # twips; 9360 = the 6.5 in text column
    grid = tbl.find(W + "tblGrid")
    if grid is not None:
        for gc in grid.findall(W + "gridCol"):
            grid.remove(gc)
        for wd in widths:
            etree.SubElement(grid, W + "gridCol").set(W + "w", str(wd))

    def row(proto, cells, bold):
        tr = copy.deepcopy(proto)
        tcs = tr.findall(W + "tc")
        keep = copy.deepcopy(tcs[0])
        for tc in tcs:
            tr.remove(tc)
        for wd, txt in zip(widths, cells):
            tc = copy.deepcopy(keep)
            tcW = tc.find(W + "tcPr/" + W + "tcW")
            if tcW is not None:
                tcW.set(W + "w", str(wd))
                tcW.set(W + "type", "dxa")
            for p in tc.findall(W + "p"):
                tc.remove(p)
            tc.append(zero_indent(clone(proto_p, ("**%s**" % txt) if bold else txt)))
            tr.append(tc)
        return tr

    tbl.append(row(header, ("Ph.", "Activity", "Deliverable"), True))
    for ph, act, deliv in PLAN:
        tbl.append(row(blank, (ph, act, deliv), False))
    fit_table(tbl)      # this table is ours, not the template's: pin it either way
    return tbl


# ----------------------------------------------------------------------------- build

def build_body(body, has_fig: bool, rel_id: str, fit: bool):
    """Return the list of elements that will replace the template's body."""
    kids = [el for el in body if etree.QName(el).localname in ("p", "tbl")]

    def find(needle, start=0):
        for i in range(start, len(kids)):
            if etree.QName(kids[i]).localname == "p" and needle in text_of(kids[i]):
                return i
        raise AssertionError(f"template paragraph not found: {needle!r}")

    # Prototypes, located by their own text so a template tweak fails loudly.
    P_NUM1 = kids[find("Project Group ID")]
    TBL = next(k for k in kids if etree.QName(k).localname == "tbl")
    P_ABS = kids[find("Abstract(150 words)")]
    P_NUM8 = kids[find("Problem Definition")]
    P_BODY = kids[find("pervasive Smartphone")]
    P_SUB = kids[find("Design an algorithm for IMU")]
    P_REF = copy.deepcopy(kids[find("SignalGuru")])
    if fit:                                 # template has right="-630": 31 pt of
        ref_ind = P_REF.find(W + "pPr/" + W + "ind")   # reference text printed
        if ref_ind is not None:                        # into the right margin
            ref_ind.set(W + "right", "0")
    P_SIGN = kids[find("Name & Sign of Student")]
    assert etree.QName(TBL).localname == "tbl"

    out = []

    # ---- cover page: keep the template's paragraphs, fill in what is ours -----
    cover_end = find("Project Group ID")
    subs = {
        "(Title of Project)": TITLE,
        "(Roll No and Name of Student)": PH + " \u2014 Roll No. and Name of each student",
        "Guide Name": PH + " \u2014 Guide Name",
    }
    for el in kids[:cover_end]:
        p = copy.deepcopy(el)
        t = text_of(p).strip()
        if t in subs:
            set_text(p, subs[t])
        out.append(p)

    def head1(s):
        out.append(clone(P_NUM1, s))

    def head8(s):
        p = clone(P_NUM8, s)
        if fit:
            pPr = p.find(W + "pPr")
            sp = pPr.find(W + "spacing")
            if sp is not None:
                sp.set(W + "after", "120")
            # The level right-aligns its label, so a wide numeral ("VIII.") grows
            # leftward from (left - hanging); a small hanging moves that anchor right.
            put(pPr, "ind", PPR_ORDER, left="720", hanging="120")
        out.append(p)

    def body_ps(items):
        for s in items:
            out.append(clone(P_BODY, s))
        out.append(clone(P_BODY, ""))

    def subs_ps(items):
        for s in items:
            out.append(clone(P_SUB, s))
        out.append(clone(P_BODY, ""))

    # ---- items 1-7 -----------------------------------------------------------
    head1("Project Group ID : " + PH)
    head1("Title of the project : " + TITLE)
    head1("Domain : Information Security and Digital Image Forensics "
          "(Multimedia Security)")
    head1("Team Member")
    out.append(copy.deepcopy(TBL))
    out.append(clone(P_BODY, ""))
    head1("Sponsorship details, if any (Name, External Guide name and Designation "
          "with Signature, e-Mail ID)")
    out.append(clone(P_BODY, "None. This is an in-house academic project carried "
                             "out within the Department of Computer Engineering, "
                             "with no external sponsor."))
    out.append(clone(P_BODY, ""))
    head1("Internal Guide Name (with signature of approval) : " + PH)
    head1("Type of Project : Research and development \u2014 in-house software "
          "project with an experimental evaluation component.")
    out.append(clone(P_BODY, ""))

    # ---- abstract and keywords ----------------------------------------------
    out.append(clone(P_ABS, "Abstract (150 words)"))
    out.append(clone(P_BODY, ABSTRACT))
    out.append(clone(P_BODY, ""))
    out.append(clone(P_ABS, "Keywords (5 to 10) :"))
    out.append(clone(P_BODY, KEYWORDS))
    out.append(clone(P_BODY, ""))

    # ---- numbered sections ---------------------------------------------------
    head8("Problem Definition")
    body_ps(PROBLEM)

    head8("Process Diagram, System architecture, List of modules, and "
          "functionalities")
    out.append(clone(P_BODY, ARCH_INTRO))
    if has_fig:
        px_w, px_h = png_size(FIG)
        cx = TEXT_W_EMU
        out.append(drawing_paragraph(P_BODY, rel_id, cx, int(cx * px_h / px_w)))
        cap = clone(P_BODY, "Figure 1: System architecture \u2014 the four stages to "
                            "be implemented, and the data that crosses between them.")
        cpPr = cap.find(W + "pPr")
        if cpPr is not None:
            put(cpPr, "jc", PPR_ORDER, val="center")
        out.append(cap)
        out.append(clone(P_BODY, ""))
    body_ps(ARCH_AFTER)
    out.append(clone(P_BODY, "**List of modules and their functionality.** The "
                             "implementation will be split into nine modules, each "
                             "independently testable:"))
    subs_ps(MODULES)

    head8("Literature survey (Study, Current market survey: similar systems / "
          "products available, their pros and cons)")
    body_ps(LIT)
    body_ps(MARKET)

    head8("Objectives")
    subs_ps(OBJECTIVES)

    head8("Scope of the project")
    body_ps(SCOPE)

    head8("Software and hardware requirements")
    subs_ps(REQUIREMENTS)

    head8("Expected Outcomes")
    body_ps(OUTCOMES)

    head8("Probable date of completion")
    out.append(clone(P_BODY, PH + " \u2014 as per the departmental academic "
                                  "calendar. The work is planned in nine phases:"))
    out.append(plan_table(TBL, P_BODY))
    out.append(clone(P_BODY, ""))

    head8("References (In IEEE Format only)")
    for r in REFERENCES:
        out.append(clone(P_REF, r))

    # ---- signature line ------------------------------------------------------
    for _ in range(3):
        out.append(clone(P_BODY, ""))
    out.append(copy.deepcopy(P_SIGN))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-pdf", action="store_true")
    ap.add_argument("--fit-margins", action="store_true",
                    help="pull the template's own out-of-margin indents back inside")
    args = ap.parse_args()

    assert TEMPLATE.exists(), f"missing template: {TEMPLATE}"
    OUTDIR.mkdir(parents=True, exist_ok=True)
    docx = OUTDIR / "Project_Proposal.docx"

    zin = zipfile.ZipFile(TEMPLATE)
    parts = {n: zin.read(n) for n in zin.namelist()}
    zin.close()

    has_fig = FIG.exists()
    rel_id = "rIdArch"
    if has_fig:
        parts["word/media/architecture.png"] = FIG.read_bytes()
        ct = parts["[Content_Types].xml"].decode("utf-8")
        if 'Extension="png"' not in ct:
            ct = ct.replace("<Default Extension=\"rels\"",
                            "<Default Extension=\"png\" ContentType=\"image/png\"/>"
                            "<Default Extension=\"rels\"", 1)
            parts["[Content_Types].xml"] = ct.encode("utf-8")
        rels = parts["word/_rels/document.xml.rels"].decode("utf-8")
        rels = rels.replace(
            "</Relationships>",
            f'<Relationship Id="{rel_id}" Type="http://schemas.openxmlformats.org/'
            'officeDocument/2006/relationships/image" Target="media/architecture.png"/>'
            "</Relationships>")
        parts["word/_rels/document.xml.rels"] = rels.encode("utf-8")
    else:
        print("  ! architecture.png missing -- proposal will have no figure")

    doc = etree.fromstring(parts["word/document.xml"])
    body = doc.find(W + "body")
    sect = body.find(W + "sectPr")          # keeps Letter size and 1 in margins
    new = build_body(body, has_fig, rel_id, args.fit_margins)
    for el in list(body):
        body.remove(el)
    for el in new:
        body.append(el)
    for tbl in body.iter(W + "tbl"):
        for p in tbl.iter(W + "p"):
            zero_indent(p)      # cell paragraphs must not inherit a first-line indent
        if args.fit_margins:
            ti = tbl.find(W + "tblPr/" + W + "tblInd")
            if ti is not None and int(ti.get(W + "w", "0")) < 0:
                ti.set(W + "w", "0")
            fit_table(tbl)
    if args.fit_margins:
        for ind in body.iter(W + "ind"):
            for side in ("left", "right", "start", "end"):
                if int(ind.get(W + side, "0")) < 0:
                    ind.set(W + side, "0")
    if sect is not None:
        body.append(sect)

    parts["word/document.xml"] = etree.tostring(
        doc, xml_declaration=True, encoding="UTF-8", standalone=True)

    with zipfile.ZipFile(docx, "w", zipfile.ZIP_DEFLATED) as z:
        for name, data in parts.items():
            z.writestr(name, data)
    print(f"  wrote {docx.relative_to(ROOT)}  {docx.stat().st_size // 1024} KB")

    if not args.skip_pdf:
        assert SOFFICE.exists(), f"LibreOffice not found at {SOFFICE}"
        subprocess.run([str(SOFFICE), "--headless", "-env:UserInstallation="
                        "file:///E:/tools/lo-profile", "--convert-to", "pdf",
                        "--outdir", str(OUTDIR), str(docx)],
                       check=True, capture_output=True, timeout=300)
        pdf = OUTDIR / "Project_Proposal.pdf"
        assert pdf.exists(), "LibreOffice produced no PDF"
        print(f"  wrote {pdf.relative_to(ROOT)}  {pdf.stat().st_size // 1024} KB")

    print(f"  template geometry: "
          f"{'pulled inside the margins' if args.fit_margins else 'exactly as issued'}")
    return check(docx, args.fit_margins)


# ----------------------------------------------------------------------------- check

def check(docx: Path, fit: bool) -> int:
    """Assert the things that have silently broken before."""
    z = zipfile.ZipFile(docx)
    doc = etree.fromstring(z.read("word/document.xml"))
    body = doc.find(W + "body")
    paras = body.findall(W + "p")
    full = "\n".join(text_of(p) for p in paras)
    tbls = body.findall(W + "tbl")

    fails = ran = 0
    def want(cond, label):
        nonlocal fails, ran
        ran += 1
        if not cond:
            fails += 1
            print(f"  FAIL  {label}")

    want("Project Proposal" in full, "cover heading present")
    want(TITLE in full, "title on cover")
    want("B.E. in Computer Engineering" in full, "degree line kept")
    want("Ajeenkya D Y Patil" in full, "institute line kept")
    want("AY 2026-27" in full, "academic year kept")
    want("(Title of Project)" not in full, "title placeholder replaced")
    want("(Roll No and Name of Student)" not in full, "student placeholder replaced")
    want("Smartphone" not in full, "template's sample content removed")
    want("SignalGuru" not in full, "template's sample references removed")

    for head in ("Project Group ID", "Title of the project", "Domain",
                 "Team Member", "Sponsorship details", "Internal Guide Name",
                 "Type of Project", "Abstract (150 words)", "Keywords (5 to 10)",
                 "Problem Definition", "Process Diagram", "Literature survey",
                 "Objectives", "Scope of the project",
                 "Software and hardware requirements", "Expected Outcomes",
                 "Probable date of completion", "References"):
        want(head in full, f"section present: {head}")

    want("Name & Sign of Student" in full, "signature line present")
    words = len(ABSTRACT.split())
    want(140 <= words <= 165, f"abstract is ~150 words (it is {words})")
    want("'" not in full.replace("&#39;", ""), "no straight apostrophes")
    want("*" not in full, "no literal ** markers leaked through")
    want(len(tbls) == 2, f"two tables (team, plan); found {len(tbls)}")
    want("[1] J. Fridrich" in full, "reference [1] present")
    want("[18] University of Southern California" in full, "reference [18] present")
    want(full.count("[TO BE FILLED]") == 5, f"5 fill-in fields; "
         f"found {full.count('[TO BE FILLED]')}")
    want("word/media/architecture.png" in z.namelist(), "architecture image embedded")
    want("image/png" in z.read("[Content_Types].xml").decode(), "png content type")

    # Proposal voice: the past-tense report phrasing must not survive.
    for banned in ("results measured to date", "Phases 1--6 are complete",
                   "is 43.17", "yields zero false positives"):
        want(banned not in full, f"report-voice phrase absent: {banned!r}")
    want(full.count("will ") >= 25, f"proposal voice ({full.count('will ')} 'will')")

    # Every cell paragraph inside a table must zero the body's first-line indent,
    # or the first line starts short and the cell wraps early.
    bad = 0
    for tbl in tbls:
        for p in tbl.iter(W + "p"):
            ind = p.find(W + "pPr/" + W + "ind")
            if ind is None or ind.get(W + "firstLine") not in ("0", None):
                if ind is None or ind.get(W + "firstLine") != "0":
                    bad += 1
    want(bad == 0, f"table cells zero the first-line indent ({bad} do not)")

    def is_bold(p):
        r = p.find(W + "r")
        return r is not None and r.find(W + "rPr/" + W + "b") is not None
    heads = [p for p in paras if text_of(p).strip().startswith(
        ("Project Group ID", "Problem Definition", "Process Diagram", "Objectives",
         "Expected Outcomes", "References"))]
    want(len(heads) >= 6 and all(is_bold(p) for p in heads),
         "numbered headings are bold")
    neg = [p for p in body.iter(W + "ind")
           if any(int(p.get(W + k, "0")) < 0 for k in ("left", "right", "start", "end"))]
    tneg = [t for t in body.iter(W + "tblInd") if int(t.get(W + "w", "0")) < 0]
    if fit:
        want(not neg, f"no negative indent survives ({len(neg)} do)")
        want(not tneg, f"no negative table indent survives ({len(tneg)} do)")
    else:
        # exactly as issued: the template's own out-of-margin values are intact
        # 20 cover paragraphs (left -540, right -630) + 18 references (right -630)
        want(len(neg) == 38, f"template's negative indents kept ({len(neg)} of 38)")
        want(len(tneg) == 2, f"template's 2 negative table indents kept ({len(tneg)})")
    plan = tbls[1]
    cols = [int(c.get(W + "w")) for c in plan.iter(W + "gridCol")]
    want(sum(cols) == 9360, f"plan table columns sum to the text block "
                            f"({sum(cols)} twips)")
    want(plan.find(W + "tblPr/" + W + "tblLayout") is not None,
         "plan table has a fixed layout")

    misordered = 0
    for parent, order in ((W + "pPr", PPR_ORDER), (W + "tblPr", TBLPR_ORDER)):
        for el in body.iter(parent):
            seen = [order.index(etree.QName(c).localname) for c in el
                    if etree.QName(c).localname in order]
            if seen != sorted(seen):
                misordered += 1
    want(misordered == 0, f"pPr/tblPr children in schema order ({misordered} are not)")

    print(f"  {ran} checks, {fails} failures")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
