r"""Flatten paper/IEEE_Paper.tex into one self-contained paper/IEEE_Paper_standalone.tex.

The committed paper deliberately pulls its numbers in from the generated grid --
five \input{../output/tables/*.tex} and two \includegraphics{../output/figures/*.pdf}
-- so it can never disagree with output/. That is right for the repository and
wrong for anywhere you can only hand over a single file: a converter or a
single-file Overleaf upload reports

    File `../output/tables/imperceptibility.tex' not found.

and stops. This script produces the single-file form:

  - each table is spliced in VERBATIM, byte for byte, so the flattened paper
    cannot drift from output/tables/ through a transcription slip;
  - each figure goes through one \figorbox macro that tries ./, then the
    repository path, then draws a labelled box -- a missing PDF becomes a
    visible placeholder instead of a failed compile.

Nothing else about the document changes: same IEEEtran conference class, same
packages, same text, same bibliography. make_tables.py still owns
output/tables/; run this afterwards to refresh the flattened copy.

Usage:  python src/make_standalone.py
Exit code is nonzero if any structural check below fails.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "paper" / "IEEE_Paper.tex"
DST = ROOT / "paper" / "IEEE_Paper_standalone.tex"

tex = SRC.read_text(encoding="utf-8")

# ---- 1. splice the tables --------------------------------------------------
spliced = []


def splice(m):
    rel = m.group(1)
    body = (ROOT / "output" / "tables" / rel).read_text(encoding="utf-8").strip("\n")
    spliced.append(rel)
    return ("%% ---- inlined from output/tables/%s (generated by make_tables.py) ----\n"
            % rel) + body


tex, n_tab = re.subn(r"\\input\{\.\./output/tables/([A-Za-z0-9_]+\.tex)\}", splice, tex)

# ---- 2. figures: one guarded macro, declared with the packages -------------
MACRO = r"""
% A single-file build may or may not have the figure PDFs beside it. Try the
% upload location, then the repository layout, then draw a labelled box -- so a
% missing image degrades to a placeholder instead of killing the compile.
\newcommand{\figorbox}[2]{%
  \IfFileExists{#1}{\includegraphics[width=\columnwidth]{#1}}{%
  \IfFileExists{../output/figures/#1}{\includegraphics[width=\columnwidth]{../output/figures/#1}}{%
  \fbox{\parbox[c][0.5\columnwidth][c]{0.93\columnwidth}{\centering\footnotesize
    [Figure not uploaded: \texttt{#2}]\\[2pt]
    Upload it beside this \texttt{.tex} to render it.}}}}%
}
"""
tex = tex.replace("\n\\begin{document}", MACRO + "\n\\begin{document}", 1)


def fig(m):
    fname = m.group(1)
    return "\\figorbox{%s}{%s}" % (fname, fname.replace("_", r"\_"))


tex, n_fig = re.subn(
    r"\\includegraphics\[width=\\columnwidth\]\{\.\./output/figures/([A-Za-z0-9_]+\.pdf)\}",
    fig, tex)

# ---- 3. the upload note in the source now describes the wrong workflow ----
OLD_NOTE = """% Figures and tables in this section are generated by make_tables.py / make_figures.py into
% output/tables/ and output/figures/ and \\input directly, so the paper always matches the
% committed result grid. Overleaf users: upload the contents of output/tables/ and
% output/figures/ alongside this .tex file, preserving the ../output/... relative path
% (or add a \\graphicspath / adjust the \\input paths to match the uploaded layout)."""
NEW_NOTE = """% SELF-CONTAINED BUILD -- generated by src/make_standalone.py from
% paper/IEEE_Paper.tex; edit that file, not this one. Every table below is
% spliced in verbatim from output/tables/ (generated by make_tables.py), so this
% file needs no companion .tex files at all: upload or convert it alone. The two
% figures are optional -- put recovery_vs_ratio.pdf and qualitative_strip.pdf
% beside this file to render them, or compile without them and each becomes a
% labelled placeholder box. Re-run src/make_standalone.py after regenerating the
% experiment grid, so the inlined numbers never drift from output/tables/."""
assert OLD_NOTE in tex, "the upload note in IEEE_Paper.tex moved -- update OLD_NOTE"
tex = tex.replace(OLD_NOTE, NEW_NOTE, 1)

DST.write_text(tex, encoding="utf-8")

# ---- 4. structural checks -------------------------------------------------
# There is no LaTeX installation here (the paper is compiled on Overleaf), so
# these stand in for a compile: they catch the failure modes a splice can
# actually introduce -- a table that did not land, an unbalanced environment or
# brace, a dangling \ref, and a row whose & count disagrees with its column spec.
fails = []


def ck(cond, label, extra=""):
    print(("  ok   " if cond else "  FAIL ") + label + (f"  {extra}" if extra else ""))
    if not cond:
        fails.append(label)


ck(n_tab == 5, "all five \\input tables spliced", f"{n_tab}: {spliced}")
ck(n_fig == 2, "both \\includegraphics rerouted", n_fig)
ck("\\input{" not in tex, "no \\input left anywhere")
# The only legitimate survivor is \figorbox's second fallback branch -- twice on
# that line, once in the \IfFileExists test and once in the \includegraphics it
# guards. Anywhere else and the file still depends on the repository layout.
outside = [ln for ln in tex.splitlines() if "../output" in ln and "IfFileExists" not in ln]
ck(not outside, "no ../output path outside the \\figorbox fallback", outside)
ck(tex.count("../output") == 2, "only the fallback branch's two ../output uses remain",
   tex.count("../output"))
ck(tex.count(r"\documentclass[conference]{IEEEtran}") == 1, "still IEEEtran conference class")

for env in ("document", "tabular", "table", "figure", "thebibliography", "abstract",
            "IEEEkeywords", "equation", "enumerate", "itemize"):
    b = len(re.findall(r"\\begin\{%s\}" % env, tex))
    e = len(re.findall(r"\\end\{%s\}" % env, tex))
    ck(b == e, f"\\begin/\\end {{{env}}} balanced", f"{b}/{e}")

ck(tex.count(r"\begin{tabular}") == 5, "five tabular environments present",
   tex.count(r"\begin{tabular}"))
ck(tex.count(r"\begin{table}") == 5, "five table floats present", tex.count(r"\begin{table}"))
ck(tex.count(r"\begin{figure}") == 2, "two figure floats present")

labels = set(re.findall(r"\\label\{([^}]+)\}", tex))
refs = (set(re.findall(r"\\ref\{([^}]+)\}", tex))
        | set(re.findall(r"\\eqref\{([^}]+)\}", tex)))
ck(refs <= labels, "every \\ref/\\eqref resolves to a \\label", sorted(refs - labels))
for lab in ("tab:imperceptibility", "tab:localization", "tab:null", "tab:baseline",
            "tab:ablation", "fig:recovery_vs_ratio", "fig:qualitative"):
    ck(lab in labels, f"label {lab} survived")

cites = set()
for m in re.findall(r"\\cite\{([^}]+)\}", tex):
    cites |= {c.strip() for c in m.split(",")}
ck(cites <= set(re.findall(r"\\bibitem\{([^}]+)\}", tex)), "every \\cite has a \\bibitem",
   sorted(cites - set(re.findall(r"\\bibitem\{([^}]+)\}", tex))))

# the spliced tables really carry their numbers, rather than being empty
for needle in ("43.17", "0.9824", "1802240", "0.00000166", "26.80", "Korus"):
    ck(needle in tex, f"table content present: {needle}")

# every body row's cell count must equal its column spec, or LaTeX stops with
# "Extra alignment tab has been changed to \cr"
RULES = r"\\(?:top|mid|bottom)rule|\\addlinespace"
mismatched = []
for spec, body in re.findall(r"\\begin\{tabular\}\{([^}]*)\}(.*?)\\end\{tabular\}", tex, re.S):
    ncol = len(re.findall(r"[lcrp]", re.sub(r"\{[^}]*\}", "", spec)))
    for row in body.split("\\\\"):
        core = re.sub(r"(?m)^\s*%.*$", "", row).strip()
        while re.match(r"^(?:" + RULES + r")", core):
            core = re.sub(r"^(?:" + RULES + r")\s*", "", core).strip()
        if not core:
            continue
        # \& is a literal ampersand in prose ("Aminuddin \& Ernawan"), not a separator
        cells = re.sub(r"\\&", "", core).count("&") + 1
        cells += sum(int(n) - 1 for n in re.findall(r"\\multicolumn\{(\d+)\}", core))
        if cells != ncol:
            mismatched.append(f"{spec!r} declares {ncol}, row has {cells}: {core[:60]}")
ck(not mismatched, "every tabular row matches its column spec", mismatched)

depth, underflow, prev = 0, False, ""
for ch in tex:
    if prev != "\\":
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            underflow = underflow or depth < 0
    prev = "" if prev == "\\" else ch
ck(depth == 0 and not underflow, "braces balanced across the whole file", depth)

print(f"\n{DST.relative_to(ROOT)}  {DST.stat().st_size / 1024:.1f} KB, "
      f"{len(tex.splitlines())} lines, {len(fails)} failures")
print("STANDALONE OK" if not fails else "FAIL: " + "; ".join(fails))
sys.exit(1 if fails else 0)
