"""Generates LaTeX `tabular` BODIES for the paper -- never a whole `table` float.

Each output file is a self-contained `\\begin{tabular}...\\end{tabular}` (booktabs
style, matching paper/IEEE_Paper.tex's existing \\usepackage{booktabs}), meant to be
\\input{} inside a hand-written `\\begin{table}...\\caption{}\\label{}...\\end{table}`.
This module never writes a caption or a label -- those are hand-tuned in the paper and
must never be clobbered by a regeneration here.

main() calls sanity_gate.run_checks() FIRST and refuses to write anything if a hard/
structural check fails. This is deliberately not a CI system, just one function call --
but it makes "generate tables from numbers nobody sanity-checked" structurally
impossible through this file's intended entry point.
"""

import argparse
import statistics
from pathlib import Path

import sanity_gate
from metrics import aggregate_by, load_runs_csv

ROOT = Path(__file__).resolve().parent.parent
TABLES_DIR = ROOT / "output" / "tables"

MAIN_BLOCK = 8
ABLATION_BLOCK = 4
MAIN_KEY_ID = 0
RATIOS = ("0.10", "0.25", "0.50")

# Readable labels matching the paper's own prose (see IEEE_Paper.tex, recall discussion).
TAMPER_LABELS = {
    "splice": "Copy-paste splicing",
    "inpaint_removal": "Object removal",
    "crop_refill": "Crop-and-refill",
    "noise": "Noise corruption",
}
TAMPER_ORDER = ("splice", "inpaint_removal", "crop_refill", "noise")


# ---------------------------------------------------------------------------
# LaTeX helpers
# ---------------------------------------------------------------------------

_LATEX_SPECIALS = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


def esc(text: str) -> str:
    """Escape LaTeX special characters in a text cell (backslash first, or double-escapes)."""
    out = str(text)
    out = out.replace("\\", _LATEX_SPECIALS["\\"])
    for ch, rep in _LATEX_SPECIALS.items():
        if ch == "\\":
            continue
        out = out.replace(ch, rep)
    return out


HEADER_COMMENT = "% generated by make_tables.py -- do not edit by hand\n"


def _fmt(val: float, decimals: int) -> str:
    if val != val:  # NaN
        return "--"
    if val in (float("inf"), float("-inf")):
        return r"$\infty$"
    return f"{val:.{decimals}f}"


def _fmt_pm(agg: dict | None, decimals: int) -> str:
    """'mean $\\pm$ std', or '--' if there is no data for this group."""
    if agg is None or agg["n"] == 0:
        return "--"
    return f"{_fmt(agg['mean'], decimals)} $\\pm$ {_fmt(agg['std'], decimals)}"


def _write(name: str, body: str) -> Path:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLES_DIR / name
    path.write_text(HEADER_COMMENT + body, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Table 1: imperceptibility.tex
# ---------------------------------------------------------------------------

def build_imperceptibility(rows: list[dict]) -> str:
    """Per-image PSNR/SSIM (8 USC-SIPI shown) + a mean row over all 32 corpus images."""
    # Canonical embed per image: block=8 (the main config), key=0 (the main-grid key).
    # wm_psnr/wm_ssim are identical across every row sharing (image, variant, block,
    # key) -- embed_image() is cached by exactly that tuple -- so any matching row works.
    src = [r for r in rows if int(r["block_size"]) == MAIN_BLOCK and int(r["key_id"]) == MAIN_KEY_ID]
    psnr = aggregate_by(src, ("image_name", "recovery_variant"), "wm_psnr")
    ssim = aggregate_by(src, ("image_name", "recovery_variant"), "wm_ssim")

    usc_names = sorted({r["image_name"] for r in src if r["dataset"] == "usc_sipi"})
    all_names = sorted({r["image_name"] for r in src})

    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Image & PSNR-A (dB) & SSIM-A & PSNR-B (dB) & SSIM-B \\",
        r"\midrule",
    ]
    for name in usc_names:
        pa = psnr.get((name, "A")); sa = ssim.get((name, "A"))
        pb = psnr.get((name, "B")); sb = ssim.get((name, "B"))
        # Plain values, no "$\pm$ 0.00": embedding is deterministic given
        # (image, variant, block, key), so a per-image std over identical rows is
        # exactly zero and printing it is noise that invites a reviewer question.
        lines.append(f"{esc(name.capitalize())} & {_fmt(pa['mean'], 2) if pa else '--'} & "
                     f"{_fmt(sa['mean'], 4) if sa else '--'} & "
                     f"{_fmt(pb['mean'], 2) if pb else '--'} & "
                     f"{_fmt(sb['mean'], 4) if sb else '--'} \\\\")
    # mean row: unweighted mean OVER THE 32 PER-IMAGE MEANS, not over underlying rows --
    # every image should count once regardless of how many CSV rows reference it.
    def _corpus_mean(agg_table: dict, variant: str) -> float:
        vals = [agg_table[(n, variant)]["mean"] for n in all_names if (n, variant) in agg_table]
        return statistics.mean(vals) if vals else float("nan")

    mean_pa, mean_sa = _corpus_mean(psnr, "A"), _corpus_mean(ssim, "A")
    mean_pb, mean_sb = _corpus_mean(psnr, "B"), _corpus_mean(ssim, "B")
    lines += [
        r"\midrule",
        rf"\textbf{{Mean ({len(all_names)} images)}} & \textbf{{{_fmt(mean_pa, 2)}}} & "
        rf"\textbf{{{_fmt(mean_sa, 4)}}} & \textbf{{{_fmt(mean_pb, 2)}}} & "
        rf"\textbf{{{_fmt(mean_sb, 4)}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    # Corpus note, per spec: 32 images total (8 USC-SIPI shown individually above + 24
    # Kodak folded only into the mean row), not the 40 some published corpora report.
    note = "% corpus is 32 images (8 USC-SIPI + 24 Kodak), not 40 -- the mean row above averages all 32\n"
    return note + "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table 2: localization_recovery.tex
# ---------------------------------------------------------------------------

def build_localization_recovery(rows: list[dict]) -> str:
    """4 tamper classes x 3 ratios, Variant A, main grid (block=8) only."""
    main_a = [r for r in rows if r["condition"] == "tamper" and r["recovery_variant"] == "A"
             and int(r["block_size"]) == MAIN_BLOCK]

    cols = [("block_precision", 3), ("block_recall", 3), ("block_f1", 3), ("block_iou", 3),
            ("recoverability_rate", 3), ("psnr_in_region", 2), ("psnr_whole_unmarked", 2)]
    aggs = {key: aggregate_by(main_a, ("tamper_class", "tamper_ratio_nominal"), key) for key, _ in cols}

    lines = [
        r"\begin{tabular}{llccccccc}",
        r"\toprule",
        r"Tamper Class & Ratio & Prec. & Recall & F1 & IoU & $\rho$ & "
        r"PSNR$_\Omega$ (dB) & PSNR$_{\mathrm{unmarked}}$ (dB) \\",
        r"\midrule",
    ]
    for cls in TAMPER_ORDER:
        for i, ratio_s in enumerate(RATIOS):
            key = (cls, ratio_s)
            label = esc(TAMPER_LABELS[cls]) if i == 0 else ""
            cells = [_fmt_pm(aggs[k].get(key), d) for k, d in cols]
            lines.append(f"{label} & {ratio_s} & " + " & ".join(cells) + r" \\")
        if cls != TAMPER_ORDER[-1]:
            lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}"]

    # Footnote data: mean +/- std ACHIEVED ratio per NOMINAL bucket. tamper_ratio_achieved
    # is deliberately kept as a string by metrics.load_runs_csv (see its NUMERIC_FIELDS
    # comment), so it is converted here, not aggregated via aggregate_by.
    achieved_notes = []
    for ratio_s in RATIOS:
        vals = [float(r["tamper_ratio_achieved"]) for r in main_a if r["tamper_ratio_nominal"] == ratio_s]
        if vals:
            mean = statistics.mean(vals)
            std = statistics.pstdev(vals) if len(vals) >= 2 else 0.0
            achieved_notes.append(f"{ratio_s} (achieved {mean:.3f} $\\pm$ {std:.3f})")
        else:
            achieved_notes.append(f"{ratio_s} (achieved: no data yet)")
    footnote = ("% Achieved tamper ratio per nominal bucket -- grouping by the nominal value is\n"
               "% never exact area matching: " + "; ".join(achieved_notes) + "\n")
    return footnote + "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table 3: null_condition.tex
# ---------------------------------------------------------------------------

def build_null_condition(rows: list[dict]) -> str:
    """Null-condition false-positive rates + rule-of-three 95% upper bound on 3/n."""
    null_rows = [r for r in rows if r["condition"] == "null"]
    n_images = len({r["image_name"] for r in null_rows})
    n_variants = len({r["recovery_variant"] for r in null_rows})
    n_keys = len({int(r["key_id"]) for r in null_rows})

    n_block_checks = sum(int(r["n_blocks_total"]) for r in null_rows)
    n_fp_blocks = sum(int(r["n_false_positive_blocks"]) for r in null_rows)
    block_fpr = (n_fp_blocks / n_block_checks) if n_block_checks else float("nan")
    px_fpr_agg = aggregate_by(null_rows, (), "px_fpr").get(())
    px_fpr = px_fpr_agg["mean"] if px_fpr_agg else float("nan")
    # Rule-of-three: with 0 observed events in n independent trials, the 95% upper
    # confidence bound on the true per-trial rate is 3/n. Pure arithmetic, no scipy.
    rule_of_three = (3.0 / n_block_checks) if n_block_checks else float("nan")

    lines = [
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"Quantity & Value \\",
        r"\midrule",
        rf"Null-condition rows & {len(null_rows)} \\",
        rf"Images $\times$ Variants $\times$ Keys & {n_images} $\times$ {n_variants} $\times$ {n_keys} \\",
        rf"Independent block verifications ($n$) & {n_block_checks} \\",
        rf"False-positive blocks (sum) & {n_fp_blocks} \\",
        rf"Block-level false-positive rate & {_fmt(block_fpr, 6)} \\",
        rf"Pixel-level false-positive rate (mean px\_fpr) & {_fmt(px_fpr, 6)} \\",
        r"\midrule",
        rf"Rule-of-three 95\% upper bound, $3/n$ & {_fmt(rule_of_three, 8)} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table 4: ablation_blocksize.tex
# ---------------------------------------------------------------------------

def build_ablation_blocksize(rows: list[dict]) -> str:
    """8x8 vs 4x4, USC-SIPI subset, Variant A: precision, recall, F1, IoU, rho, PSNR_omega."""
    usc_a = [r for r in rows if r["condition"] == "tamper" and r["recovery_variant"] == "A"
            and r["dataset"] == "usc_sipi"]
    b8 = [r for r in usc_a if int(r["block_size"]) == MAIN_BLOCK]
    b4 = [r for r in usc_a if int(r["block_size"]) == ABLATION_BLOCK]

    # PIXEL-level metrics are included deliberately: block-level precision/IoU are
    # saturated at 1.000 for BOTH block sizes, because block-level ground truth is
    # itself defined at whatever granularity is under test, so the comparison is
    # vacuous there. The trade-off the ablation exists to quantify only becomes
    # visible at pixel level, where a finer block genuinely tightens the mask.
    cols = [("block_precision", 3), ("px_precision", 4), ("px_iou", 4),
            ("recoverability_rate", 3), ("psnr_in_region", 2)]
    lines = [
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"Block Size & Blk. Prec. & Px. Prec. & Px. IoU & $\rho$ & PSNR$_\Omega$ (dB) \\",
        r"\midrule",
    ]
    for label, sub in (("8$\\times$8 (main)", b8), ("4$\\times$4 (ablation)", b4)):
        aggs = {key: aggregate_by(sub, (), key).get(()) for key, _ in cols}
        cells = [_fmt_pm(aggs[k], d) for k, d in cols]
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [
        r"\midrule",
        r"\multicolumn{6}{p{0.9\linewidth}}{\footnotesize Note: at block size 4 the "
        r"per-block payload is only 32 bits (\texttt{budget(4)}), so the authentication "
        r"tag drops from 32 to 16 bits, raising the per-block false-accept probability "
        r"from $2^{-32}$ to $2^{-16}$ -- on a $512\times512$ image with 16{,}384 blocks "
        r"that is an expected $\approx0.25$ false accepts per image. This is the honest "
        r"cost of finer localization, reported here as a finding, not omitted.} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table 5: baseline_comparison.tex
# ---------------------------------------------------------------------------

# Published values, cited verbatim from their source papers (see docstring / task brief).
_PUBLISHED = [
    ("AuSR1 (Aminuddin \\& Ernawan 2022)", "45.57", r"$\approx$0.99", "27.64",
     "worst case reported; 2$\\times$2 blocks"),
    ("Wu et al.\\ (CMC 2025)", "$>$41", "--", "$>$30 @ 50\\% tamper",
     "0\\% FPR/FNR, 100\\% detection rate"),
    ("Korus \\& Dziech (IEEE TIP 2013)", "--", "--", "37 @ 50\\% damage",
     "fountain codes, $>$10{,}000 images"),
]


def build_baseline_comparison(rows: list[dict]) -> str:
    """Our measured numbers beside published literature values."""
    # Variant A only. Averaging A and B into one figure would report a number
    # (43.69 dB) that NEITHER variant produces -- A measures 43.18 and B 44.20,
    # and they differ for a structural reason (their payload value distributions
    # differ, see the paper's imperceptibility discussion). Variant A is the
    # primary configuration, so the comparison row reports A and says so.
    main_rows = [r for r in rows if int(r["block_size"]) == MAIN_BLOCK
                 and int(r["key_id"]) == MAIN_KEY_ID and r["recovery_variant"] == "A"]
    wm_psnr = aggregate_by(main_rows, (), "wm_psnr").get(())
    wm_ssim = aggregate_by(main_rows, (), "wm_ssim").get(())

    tamper_a_50 = [r for r in rows if r["condition"] == "tamper" and r["recovery_variant"] == "A"
                  and int(r["block_size"]) == MAIN_BLOCK and r["tamper_ratio_nominal"] == "0.50"]
    unmarked_50 = aggregate_by(tamper_a_50, (), "psnr_whole_unmarked").get(())
    marked_50 = aggregate_by(tamper_a_50, (), "psnr_whole_marked").get(())

    ours_psnr = f"{wm_psnr['mean']:.2f}" if wm_psnr else "--"
    ours_ssim = f"{wm_ssim['mean']:.4f}" if wm_ssim else "--"
    ours_recovered = f"{unmarked_50['mean']:.2f} @ 50\\% tamper" if unmarked_50 else "--"
    # This note used to be the hardcoded string literal "block/pixel precision/recall
    # $\geq$0.97", which is FALSE: measured pixel precision has mean 0.9489 with 78.4%
    # of main-grid rows BELOW 0.97. It was not conditioned on data, so the sanity gate
    # could never catch it -- the gate checks the CSV, never the generated LaTeX. It was
    # the only localization figure a reader of this table saw. Every number in this
    # cell is now computed from the rows in front of us.
    # ponytail: no gate on generated LaTeX -- the fix is to compute, not to add a
    # second checker. If more literals creep in here, gate the .tex files too.
    main_a = [r for r in rows if r["condition"] == "tamper" and r["recovery_variant"] == "A"
              and int(r["block_size"]) == MAIN_BLOCK]
    blk_p = aggregate_by(main_a, (), "block_precision").get(())
    blk_r = aggregate_by(main_a, (), "block_recall").get(())
    px_p = aggregate_by(main_a, (), "px_precision").get(())
    if blk_p and blk_r and px_p:
        ours_note = (f"block prec.\\ {blk_p['mean']:.4f}, recall {blk_r['mean']:.4f}, "
                     f"pixel prec.\\ {px_p['mean']:.4f} (Table~\\ref{{tab:localization}})")
    else:
        ours_note = "no main-grid tamper rows yet"
    if marked_50:
        ours_note += f"; marked (honest) output: {marked_50['mean']:.2f}~dB"

    lines = [
        r"\begin{tabular}{lcccl}",
        r"\toprule",
        r"Method & WM PSNR (dB) & WM SSIM & Recovered PSNR (dB) & Notes \\",
        r"\midrule",
    ]
    for method, psnr, ssim, rec, note in _PUBLISHED:
        lines.append(f"{method} & {psnr} & {ssim} & {rec} & {note} \\\\")
    lines.append(rf"\textbf{{Ours (measured, Variant A)}} & {ours_psnr} & {ours_ssim} & {ours_recovered} & {ours_note} \\")
    lines += [
        r"\midrule",
        r"\multicolumn{5}{p{0.9\linewidth}}{\footnotesize AuSR1, AuSR3 and Wu et al.\ "
        r"values are cited from their publications, not re-implementations. Our "
        r"``Recovered PSNR'' uses \texttt{psnr\_whole\_unmarked} -- the only quantity "
        r"comparable to those papers' whole-image, unrecoverable-region-left-as-received "
        r"convention; our default output instead marks unrecoverable regions explicitly "
        r"rather than fabricating content, which costs 10--15~dB of whole-image PSNR "
        r"relative to the unmarked figure shown here.} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

TABLE_BUILDERS = [
    ("imperceptibility.tex", build_imperceptibility),
    ("localization_recovery.tex", build_localization_recovery),
    ("null_condition.tex", build_null_condition),
    ("ablation_blocksize.tex", build_ablation_blocksize),
    ("baseline_comparison.tex", build_baseline_comparison),
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate paper LaTeX table bodies from output/runs.csv.")
    parser.add_argument("--csv", type=Path, default=sanity_gate.DEFAULT_CSV,
                        help="path to runs.csv (default: %(default)s)")
    args = parser.parse_args()

    passed, results = sanity_gate.run_checks(args.csv)
    if not passed:
        failed = [r for r in results if r["status"] == "FAIL"]
        print("#" * 78)
        print("# ABORTED -- sanity_gate reported hard/structural failures. Writing NOTHING.")
        print("# Fix the underlying data or bands before generating tables from it.")
        print("#" * 78)
        for r in failed:
            print(f"  FAIL: {r['name']} -- {r['detail']}")
        raise SystemExit(1)

    rows = load_runs_csv(args.csv)
    print(f"sanity_gate passed ({len(rows)} rows) -- generating tables into {TABLES_DIR}")
    for filename, builder in TABLE_BUILDERS:
        path = _write(filename, builder(rows))
        print(f"  wrote {path}")


if __name__ == "__main__":
    main()
