r"""Keep the tables inside paper/IEEE_Paper.tex identical to output/tables/.

The paper is a single self-contained .tex: one file, no \input, no companion
files, so a converter or a one-file Overleaf upload works. It used to read the
tables in with \input{../output/tables/*.tex}, which guaranteed the printed
numbers matched the committed result grid but broke every single-file tool with

    File `../output/tables/imperceptibility.tex' not found.

Inlining the tables fixes that and costs the guarantee -- unless something puts
it back. That is this script. Each table sits between a marker line

    % ---- inlined from output/tables/NAME.tex (generated by make_tables.py) ----

and its \end{tabular}; this rewrites each such block from the current file in
output/tables/, byte for byte. So after re-running the experiment grid and
make_tables.py, run this and the paper's numbers follow -- no hand-copying, no
drift. Running it when nothing changed rewrites the file identically.

It also still handles a first flattening: any surviving \input of a table, and
any \includegraphics of a figure, is converted on the way through.

Usage:  python src/sync_paper_tables.py
Exit code is nonzero if any structural check below fails.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper" / "IEEE_Paper.tex"
TABLES = ROOT / "output" / "tables"

MARK = "%% ---- inlined from output/tables/%s (generated by make_tables.py) ----"
tex = PAPER.read_text(encoding="utf-8")
refreshed, spliced = [], []


def body_of(rel):
    return (TABLES / rel).read_text(encoding="utf-8").strip("\n")


# ---- 1. refresh already-inlined tables ------------------------------------
def refresh(m):
    rel = m.group(1)
    refreshed.append(rel)
    return (MARK % rel) + "\n" + body_of(rel)


tex, n_refresh = re.subn(
    r"% ---- inlined from output/tables/([A-Za-z0-9_]+\.tex)[^\n]*----\n"
    r".*?\\end\{tabular\}",
    refresh, tex, flags=re.S)


# ---- 2. first-time flattening, if any \input or figure path survives ------
def splice(m):
    rel = m.group(1)
    spliced.append(rel)
    return (MARK % rel) + "\n" + body_of(rel)


tex, n_splice = re.subn(r"\\input\{\.\./output/tables/([A-Za-z0-9_]+\.tex)\}", splice, tex)

MACRO = r"""
% A single-file build may or may not have the figure PDFs beside it. Try the
% upload location, then the repository layout, then draw a labelled box -- so a
% missing image degrades to a placeholder instead of killing the compile.
\newcommand{\figorbox}[2]{%
  \IfFileExists{#1}{\includegraphics[width=\columnwidth]{#1}}{%
  \IfFileExists{../output/figures/#1}{\includegraphics[width=\columnwidth]{../output/figures/#1}}{%
  \fbox{\parbox[c][0.5\columnwidth][c]{0.93\columnwidth}{\centering\footnotesize
    [Figure not uploaded: \texttt{#2}]\\[2pt]
    Upload it beside this \texttt{.tex} to render it.}}}}%
}
"""
if r"\newcommand{\figorbox}" not in tex:
    tex = tex.replace("\n\\begin{document}", MACRO + "\n\\begin{document}", 1)

tex, n_fig = re.subn(
    r"\\includegraphics\[width=\\columnwidth\]\{\.\./output/figures/([A-Za-z0-9_]+\.pdf)\}",
    lambda m: "\\figorbox{%s}{%s}" % (m.group(1), m.group(1).replace("_", r"\_")), tex)

PAPER.write_text(tex, encoding="utf-8")

# ---- 3. structural checks -------------------------------------------------
# There is no LaTeX installation here (the paper is compiled on Overleaf), so
# these stand in for a compile: they catch what a splice can actually break --
# a table that did not land, an unbalanced environment or brace, a dangling
# \ref, a row whose & count disagrees with its column spec.
fails = []


def ck(cond, label, extra=""):
    print(("  ok   " if cond else "  FAIL ") + label + (f"  {extra}" if extra else ""))
    if not cond:
        fails.append(label)


ck(n_refresh + n_splice == 5, "all five tables rewritten from output/tables/",
   f"{n_refresh} refreshed {sorted(refreshed)}, {n_splice} newly spliced {sorted(spliced)}")
ck(sorted(refreshed + spliced) == sorted(p.name for p in TABLES.glob("*.tex")),
   "every file in output/tables/ is used exactly once",
   sorted(refreshed + spliced))
ck("\\input{" not in tex, "no \\input left -- the file stands alone")
# The only legitimate ../output is \figorbox's fallback branch: twice on that
# line, once in the \IfFileExists test and once in the \includegraphics it guards.
outside = [ln for ln in tex.splitlines() if "../output" in ln and "IfFileExists" not in ln]
ck(not outside, "no ../output path outside the \\figorbox fallback", outside)
ck(tex.count("../output") == 2, "only the fallback branch's two ../output uses remain",
   tex.count("../output"))
# The definition reads \newcommand{\figorbox}[2], so \figorbox{ counts uses only.
ck(tex.count(r"\newcommand{\figorbox}") == 1 and tex.count(r"\figorbox{") == 2,
   "figorbox defined once and used twice", tex.count(r"\figorbox{"))
ck(tex.count(r"\documentclass[conference]{IEEEtran}") == 1, "still IEEEtran conference class")

for env in ("document", "tabular", "table", "figure", "thebibliography", "abstract",
            "IEEEkeywords", "equation", "enumerate", "itemize"):
    b = len(re.findall(r"\\begin\{%s\}" % env, tex))
    e = len(re.findall(r"\\end\{%s\}" % env, tex))
    ck(b == e, f"\\begin/\\end {{{env}}} balanced", f"{b}/{e}")

ck(tex.count(r"\begin{tabular}") == 5, "five tabular environments present",
   tex.count(r"\begin{tabular}"))
ck(tex.count(r"\begin{table}") == 5, "five table floats present", tex.count(r"\begin{table}"))
ck(tex.count(r"\begin{figure}") == 2, "two figure floats present")

labels = set(re.findall(r"\\label\{([^}]+)\}", tex))
refs = (set(re.findall(r"\\ref\{([^}]+)\}", tex))
        | set(re.findall(r"\\eqref\{([^}]+)\}", tex)))
ck(refs <= labels, "every \\ref/\\eqref resolves to a \\label", sorted(refs - labels))
for lab in ("tab:imperceptibility", "tab:localization", "tab:null", "tab:baseline",
            "tab:ablation", "fig:recovery_vs_ratio", "fig:qualitative"):
    ck(lab in labels, f"label {lab} present")

cites = set()
for m in re.findall(r"\\cite\{([^}]+)\}", tex):
    cites |= {c.strip() for c in m.split(",")}
bibs = set(re.findall(r"\\bibitem\{([^}]+)\}", tex))
ck(cites <= bibs, "every \\cite has a \\bibitem", sorted(cites - bibs))

# the tables really carry their numbers rather than having landed empty
for needle in ("43.17", "0.9824", "1802240", "0.00000166", "26.80", "Korus"):
    ck(needle in tex, f"table content present: {needle}")

# every body row's cell count must equal its column spec, or LaTeX stops with
# "Extra alignment tab has been changed to \cr"
RULES = r"\\(?:top|mid|bottom)rule|\\addlinespace"
mismatched = []
for spec, body in re.findall(r"\\begin\{tabular\}\{([^}]*)\}(.*?)\\end\{tabular\}", tex, re.S):
    ncol = len(re.findall(r"[lcrp]", re.sub(r"\{[^}]*\}", "", spec)))
    for row in body.split("\\\\"):
        core = re.sub(r"(?m)^\s*%.*$", "", row).strip()
        while re.match(r"^(?:" + RULES + r")", core):
            core = re.sub(r"^(?:" + RULES + r")\s*", "", core).strip()
        if not core:
            continue
        # \& is a literal ampersand in prose ("Aminuddin \& Ernawan"), not a separator
        cells = re.sub(r"\\&", "", core).count("&") + 1
        cells += sum(int(n) - 1 for n in re.findall(r"\\multicolumn\{(\d+)\}", core))
        if cells != ncol:
            mismatched.append(f"{spec!r} declares {ncol}, row has {cells}: {core[:60]}")
ck(not mismatched, "every tabular row matches its column spec", mismatched)

depth, underflow, prev = 0, False, ""
for ch in tex:
    if prev != "\\":
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            underflow = underflow or depth < 0
    prev = "" if prev == "\\" else ch
ck(depth == 0 and not underflow, "braces balanced across the whole file", depth)

print(f"\n{PAPER.relative_to(ROOT)}  {PAPER.stat().st_size / 1024:.1f} KB, "
      f"{len(tex.splitlines())} lines, {len(fails)} failures")
print("PAPER OK" if not fails else "FAIL: " + "; ".join(fails))
sys.exit(1 if fails else 0)
